# Generated by Django 5.1.1 on 2024-09-21 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='company_name',
            new_name='user',
        ),
    ]
