# Generated by Django 5.1.1 on 2024-09-21 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_rename_company_name_sponsor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='size',
        ),
    ]
