# Generated by Django 5.1.1 on 2024-09-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_remove_sponsor_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='size',
            field=models.IntegerField(choices=[('1-20', '1-20'), ('20-100', '20-100'), ('100-200', '100-200'), ('200-500', '200-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], default=0),
            preserve_default=False,
        ),
    ]
