# Generated by Django 5.1.1 on 2024-09-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_sponsor_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role_level',
            field=models.CharField(choices=[('interns', 'Internships'), ('entrylevel', 'Entry Level/Graduate'), ('junior', 'Junior (1-2 Years)'), ('mid_level', 'Mid-Level (3-4 Yeara)'), ('senior', 'Senior (5-8 Years)'), ('expert', 'Expert & Leadership (9+ Years)')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='team_preferences',
            field=models.CharField(choices=[('1-20', '1-20'), ('20-100', '20-100'), ('100-200', '100-200'), ('200-500', '200-500'), ('500-1000', '500-1000'), ('1000+', '1000+')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='experience_range',
            field=models.CharField(choices=[('interns', 'Internships'), ('entrylevel', 'Entry Level/Graduate'), ('junior', 'Junior (1-2 Years)'), ('mid_level', 'Mid-Level (3-4 Yeara)'), ('senior', 'Senior (5-8 Years)'), ('expert', 'Expert & Leadership (9+ Years)')], max_length=50),
        ),
    ]
