# Generated by Django 5.1.1 on 2024-09-22 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_candidate_role_level_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='user',
            new_name='org_name',
        ),
    ]
