# Generated by Django 5.1.1 on 2024-09-22 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_rename_user_sponsor_org_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='org_name',
            new_name='user',
        ),
    ]
